localization:
  ndt_map_publisher_node:
    ros__parameters:
      map_topic: "ndt_map"
      map_pcd_file: "/opt/AutowareAuto/share/autoware_auto_avp_demo/data/autonomoustuff_parking_lot.pcd"
      map_yaml_file: "/opt/AutowareAuto/share/autoware_auto_avp_demo/data/autonomoustuff_parking_lot.yaml"
      map_frame: "map"
      map_config:
        capacity: 55000
        min_point:
          x: -130.0
          y: -130.0
          z: -3.0
        max_point:
          x: 130.0
          y: 130.0
          z: 3.0
        voxel_size:
          x: 2.0
          y: 2.0
          z: 2.0
      viz_map: True
      viz_map_topic: "viz_ndt_map"
