/**:
  ros__parameters:
    optimization_weights:
      steering: 1.0
      throttle: 1.0
      goal: 0.5
    state_bounds:
      lower:
        x_m: -300.0
        y_m: -300.0
        velocity_mps: -3.0
        heading_rad: -6.2832
        steering_rad: -0.67
      upper:
        x_m: 300.0
        y_m: 300.0
        velocity_mps: 3.0
        heading_rad: 6.2832
        steering_rad: 0.67
    command_bounds:
      lower:
        steering_rate_rps: -5.0
        throttle_mps2: -5.0
      upper:
        steering_rate_rps: 5.0
        throttle_mps2: 5.0
