/**:
  ros__parameters:
    state_frame: 'odom'
    odom_child_frame: 'base_link'
    sim_time_step_s: 0.1  # Note: This should equal the MPC output sampling time
    real_time_sim: false
    stop_and_report_time_s: 10.0 # 0.0 for infinite, simulated time in seconds
    trajectory:
      generate: false
