#!/bin/bash

current_dir=$(pwd)
repo_root_dir=$(git rev-parse --show-toplevel)

cd "${repo_root_dir}" || exit

cmake_files=$(git diff --cached --name-only --diff-filter=ACMRT | grep -E "CMakeLists.txt|\.cmake")
if [[ -n ${cmake_files} ]]; then
    echo "Running lint_cmake on the following file(s):"
    echo "--------------------------------------------"
    echo "${cmake_files}" | sed 's/^/\ -\ /g'
    echo
    if ament_lint_cmake ${cmake_files} &> /tmp/cmakelint_output; then
        echo "No errors found"
    else
        cat /tmp/cmakelint_output
        rm /tmp/cmakelint_output
        exit 1
    fi
    echo
fi

cpp_files=$(git diff --cached --name-only --diff-filter=ACMRT | grep -E "\.(c|cpp|h|hpp)$")
if [[ -n ${cpp_files} ]]; then
    echo "Running uncrustify on the following file(s):"
    echo "--------------------------------------------"
    echo "${cpp_files}" | sed 's/^/\ -\ /g'
    echo
    if ament_uncrustify --reformat ${cpp_files} &> /tmp/uncrustify_output; then
        echo "No errors found"
    else
        echo "Some files were reformatted, please check the changes and commit again"
        exit 2
    fi

    echo
    echo "Running cpplint"
    echo "---------------"
    ament_cpplint ${cpp_files} &> /tmp/cpplint_output
    if ament_cpplint ${cpp_files} &> /tmp/cpplint_output; then
        echo "No errors found"
    else
        cat /tmp/cpplint_output
        rm /tmp/cpplint_output
        exit 3
    fi
fi

cd "${current_dir}" || exit
