/**:
  ros__parameters:
    vehicle:
      cg_to_front_m: 1.367
      cg_to_rear_m: 1.367
      front_corner_stiffness: 0.1
      rear_corner_stiffness: 0.1
      mass_kg: 2120.0
      yaw_inertia_kgm2: 12.0
      width_m: 2.0
      front_overhang_m: 1.033
      rear_overhang_m: 1.021
