# config/state_estimator_test.param.yaml
---

/**:
  ros__parameters:
    # The type of the input messages. This must match the type of the "messages" topic.
    input_msg_type: "nav_msgs/msg/Odometry"

    # Specify the history size.
    history_size: 10

    # Override covariances on supported field names. Note that these fields must have a "covariance"
    # field, i.e., in this case fields "pose.covariance" and "twist.covariance" should be present
    # somewhere in the message "output_msg".
    #
    # Alternatively, "directly" can be specified to set the covariance values to the
    # "output_msg.covariance" field directly. This entry should usually appear alone.
    override_covariance:
        directly: [42.0, 42.0, ...] # Set covariance for the .covariance field directly
        pose: [42.0, 42.0, ...]  # Set covariance for the .pose field of the message
        twist: [42.0, 42.0, ...]  # Set covariance for the .twist field of the message
