---
/**:
  ros__parameters:
    topics:
      input_pose:
        - /localization/ndt_pose_with_covariance
    data_driven: true
    frame_id: "map"
    child_frame_id: "base_link"
    mahalanobis_threshold: 2.0

    process_noise_variances:
      acceleration: [2.0, 2.0]

    state_variances: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    min_speed_to_use_speed_orientation: 1.0