/**:
  ros__parameters:
    vehicle_parameters_node: "/test/vehicle_parameters_node"
    safety_factor: 1.1
    stop_margin: 12.5
    trajectory_smoother:
      kernel_std: 5.0
      kernel_size: 25
    staleness_threshold_ms: 500
    target_frame_id: "map"