/**:
  ros__parameters:
    enable_object_collision_estimator: true
    heading_weight: 0.1
    goal_distance_thresh: 3.0
    stop_velocity_thresh: 2.0
    subroute_goal_offset_lane2parking: 7.6669
    subroute_goal_offset_parking2lane: 7.6669
    include_current_state: true  # if true, the current ego state will be one of the trajectory point
    prepend_distance: 0.0        # [m] length of trajectory to keep behind ego
