/**:
  ros__parameters:
    # -- Node Configurations --
    waypoints_velocity: 5.0

    # -- A* search Configurations --
    # base configs
    use_back: true
    only_behind_solutions: false
    time_limit: 30000.0
    # robot configs
    maximum_turning_radius: 20.0
    turning_radius_size: 5
    vehicle_dimension_margin: 0.0
    # search configs
    theta_size: 48
    angle_goal_range: 0.10472
    reverse_weight: 2.0
    lateral_goal_range: 0.5
    longitudinal_goal_range: 2.0
    # costmap configs
    obstacle_threshold: 100
    distance_heuristic_weight: 1.0
