/**:
  ros__parameters:
    # -- Node Configurations --
    planning_algorithm: "astar"
    waypoints_velocity: 5.0

    # -- A* search Configurations --
    # base configs
    time_limit: 30000.0
    # robot configs
    maximum_turning_radius: 20.0
    turning_radius_size: 5 #TODO tier has 1
    vehicle_dimension_margin: 0.0
    # search configs
    theta_size: 48  #TODO tier has 144
    goal_angular_tolerance: 0.05236  #TODO maybe double (6deg)
    curve_weight: 1.2
    reverse_weight: 2.0
    goal_lateral_tolerance: 0.5
    goal_longitudinal_tolerance: 2.0
    # costmap configs
    obstacle_threshold: 100

    astar:
      use_back: true
      use_reeds_shepp: true
      only_behind_solutions: false
      distance_heuristic_weight: 1.0
