/**:
  ros__parameters:
    ip: "10.31.32.93"
    port: 8301
    cloud_size:  55000
    topic: "points_xyzi"
    frame_id: "lidar_rear"
    timeout_ms: 10
    rpm:        600
    model: "vlp16"
    ring_information: false
