/**:
  ros__parameters:
    pull_out:
      min_stop_distance: 2.0
      stop_time: 0.0
      hysteresis_buffer_distance: 1.0
      pull_out_prepare_duration: 4.0
      pull_out_duration: 2.0
      pull_out_finish_judge_buffer: 1.0
      minimum_pull_out_velocity: 2.0
      prediction_duration: 30.0
      prediction_time_resolution: 0.5
      static_obstacle_velocity_thresh: 1.5
      maximum_deceleration: 1.0
      enable_abort_pull_out: false
      enable_collision_check_at_prepare_phase: false
      use_predicted_path_outside_lanelet: false
      use_all_predicted_path: false
      use_dynamic_object: false
      enable_blocked_by_obstacle: false
      pull_out_search_distance: 30.0
      before_pull_out_straight_distance: 5.0
      after_pull_out_straight_distance: 5.0
      maximum_lateral_jerk: 2.0
      minimum_lateral_jerk: 0.5
      deceleration_interval: 15.0
