/**:
  ros__parameters:
    vehicle:
      cg_to_front_m: 1.228
      cg_to_rear_m: 1.5618
      front_corner_stiffness: 17000.0  # NOT USED
      rear_corner_stiffness: 20000.0   # NOT USED
      mass_kg: 1460.0                  # NOT USED
      yaw_inertia_kgm2: 2170.0         # NOT USED
      width_m: 2.0                     # NOT USED
      front_overhang_m: 0.5
      rear_overhang_m: 0.5