
---
lidars:
  point_cloud_fusion_node:
    ros__parameters:
      output_topic:     "points_filtered"
      input_topics:
        - "/lidar_front/points_filtered"
        - "/lidar_rear/points_filtered"
      output_frame_id:  "base_link"
      cloud_size:       55000
