# Autoware State Monitor Parameters
/**:
  ros__parameters:
    # modules_names: string array
    module_names: [
      "map",
      "sensing",
      "perception",
      "localization",
      "planning",
      "control",
      "vehicle",
      "system"
    ]

    # Topic Config
    ## names: string array
    ## configs: top level
    ### names used to declare parameter group
    #### module: string
    #### timeout[s]: double (0: none)
    #### warn_rate[hz]: double (0: none)
    topic_configs:
      names: [
        "/localization/initialpose",
        "/localization/ndt_map",
        "/localization/ndt_pose",
        "/perception/lidar_bounding_boxes",
        "/perception/points_nonground",
        "/planning/global_path",
        "/planning/trajectory",
        "/vehicle/vehicle_command",
        "/vehicle/state_report",
        "/vehicle/vehicle_kinematic_state",
      ]

      configs:
        /localization/initialpose:
          module: "localization"
          timeout: 0.0
          warn_rate: 0.0
          type: "geometry_msgs/msg/PoseWithCovarianceStamped"

        /localization/ndt_map:
          module: "localization"
          timeout: 0.0
          warn_rate: 0.0
          type: "sensor_msgs/msg/PointCloud2"
          transient_local: True

        /localization/ndt_pose:
          module: "localization"
          timeout: 1.0
          warn_rate: 5.0
          type: "geometry_msgs/msg/PoseWithCovarianceStamped"

        /perception/lidar_bounding_boxes:
          module: "perception"
          timeout: 1.0
          warn_rate: 5.0
          type: "autoware_auto_msgs/msg/BoundingBoxArray"

        /perception/points_nonground:
          module: "perception"
          timeout: 1.0
          warn_rate: 5.0
          type: "sensor_msgs/msg/PointCloud2"
          best_effort: True

        /planning/global_path:
          module: "planning"
          timeout: 0.0
          warn_rate: 0.0
          type: "autoware_auto_msgs/msg/HADMapRoute"

        /planning/trajectory:
          module: "planning"
          timeout: 1.0
          warn_rate: 5.0
          type: "autoware_auto_msgs/msg/Trajectory"

        /vehicle/vehicle_command:
          module: "vehicle"
          timeout: 1.0
          warn_rate: 5.0
          type: "autoware_auto_msgs/msg/VehicleControlCommand"

        /vehicle/state_report:
          module: "vehicle"
          timeout: 1.0
          warn_rate: 5.0
          type: "autoware_auto_msgs/msg/VehicleStateReport"
          
        /vehicle/vehicle_kinematic_state:
          module: "vehicle"
          timeout: 1.0
          warn_rate: 5.0
          type: "autoware_auto_msgs/msg/VehicleKinematicState"

    # Param Config
    ## names: string array
    ## configs: top level
    ### names used to declare parameter group
    #### module: string
    # param_configs:
    #   names: ["/vehicle_info"]
    #   configs:
    #     /vehicle_info:
    #       module: "vehicle"

    # TF Config
    ## names: string array
    ## configs: top level
    ### names used to declare parameter group
    #### module: string
    #### from: string
    #### to: string
    #### timeout[s]: double (0: none)
    tf_configs:
      names: ["map_to_base_link"]
      configs:
        map_to_base_link:
          module: "localization"
          from: "map"
          to: "base_link"
          timeout: 1.0
