# Autoware State Monitor Parameters
/**:
  ros__parameters:
    update_rate: 10.0
    th_arrived_distance_m: 2.0
    th_stopped_time_sec: 1.0
    th_stopped_velocity_mps: 0.01

    # modules_names: string array
    module_names: [
      "map",
      "sensing",
      "perception",
      "localization",
      "planning",
      "control",
      "vehicle",
      "system"
    ]

    # Param Config
    ## names: string array
    ## configs: top level
    ### names used to declare parameter group
    #### module: string
    # param_configs:
    #   names: ["/vehicle_info"]
    #   configs:
    #     /vehicle_info:
    #       module: "vehicle"

    # TF Config
    ## names: string array
    ## configs: top level
    ### names used to declare parameter group
    #### module: string
    #### from: string
    #### to: string
    #### timeout[s]: double (0: none)
    tf_configs:
      names: ["map_to_base_link"]
      configs:
        map_to_base_link:
          module: "localization"
          from: "map"
          to: "base_link"
          timeout: 1.0
