/**:
  ros__parameters:
    working_mode: "Static" # "Static" or "PolygonSub"
    # if working_mode is "Static"
    # x1, y1, x2, y2, ...
    polygon_vertices: [ 0.0, -23.916,
                        0.21031, -10.228,
                        23.8108, -6.61647,
                        10.8577, -2.18663,
                        14.7159, 21.3748,
                        6.50012, 10.4246,
                        -14.7159, 21.3748,
                        -6.8404, 10.1773,
                        -23.8108, -6.61647,
                        -10.7277, -2.58666 ] # Cute 5 corner star
#    polygon_vertices: [ -6.0, -6.0,
#                        -6.0, 6.0,
#                        6.0, 6.0,
#                        6.0, -6.0 ] # Square
#    polygon_vertices: [ 0.0, -10.2037,
#                        10.0052, -7.31549,
#                        20.0104, -4.42723,
#                        20.0104, 1.34929,
#                        20.0104, 7.1258,
#                        10.0052, 10.0141,
#                        -1.90735e-06, 12.9023,
#                        -10.0052, 10.0141,
#                        -20.0104, 7.1258,
#                        -20.0104, 1.34929,
#                        -20.0104, -4.42723,
#                        -10.0052, -7.31549 ] # Some squashed hexagon
#    polygon_vertices: [ 25.214, 15.576,
#                        5.62611, 10.7628,
#                        0.000549316, 30.133,
#                        -5.62502, 10.7628,
#                        -25.2129, 15.576,
#                        -11.2506, 1.019,
#                        -25.2129, -13.538,
#                        -5.62502, -8.72476,
#                        0.000547409, -28.095,
#                        5.62611, -8.72476,
#                        25.214, -13.538,
#                        11.2517, 1.01901 ] # 6 corner star
#    polygon_vertices: [ -8.0, -8.0,
#                        -8.0, 8.0,
#                        8.0, 0.0 ] # Triangle

    will_visualize: True


