/**:
  ros__parameters:
    heading_weight: 0.1
    min_record_distance: 0.5
    use_odom: True
    enable_object_collision_estimator: False
    goal_distance_threshold_m: 0.75
    goal_angle_threshold_rad: 1.57