/**:
  ros__parameters:
    ip: "127.0.0.1"
    port: 2368
    cloud_size:  55000
    topic: "points_xyzif"
    frame_id: "lidar_front"
    timeout_ms: 10
    rpm: 600
    model: "vlp16"
    ring_information: true
