# config/vlp16_test.param.yaml
/**:
  ros__parameters:
    ip: "255.255.255.255"
    port: 2368
    cloud_size:  100000
    topic: "points_xyzif"  # UdpDriverNode strictly expects to get the topic via `declare_parameter`.
    frame_id: "lidar_front"
    timeout_ms: 10
    rpm:        600
