/**:
  ros__parameters:
    vehicle:
      cg_to_front_m: 1.228
      cg_to_rear_m: 1.5618
      front_corner_stiffness: 0.1
      rear_corner_stiffness: 0.1
      mass_kg: 1500.0
      yaw_inertia_kgm2: 12.0
      width_m: 1.83
      front_overhang_m: 1.0
      rear_overhang_m: 1.03
    safety_factor: 1.15
    stop_margin: 20.0  # distance between control point (e.g. CoG/base_link) and obstacle
    trajectory_smoother:
      kernel_std: 5.0
      kernel_size: 25
    staleness_threshold_ms: 1000
    target_frame_id: "map"
