---
/**:
  ros__parameters:
    input_msg_type: "PoseWithCovarianceStamped"
    override_covariance:
        pose: [
          1.0, 0.0, 0.0, 0.0, 0.0, 0.0,  # x
          0.0, 1.0, 0.0, 0.0, 0.0, 0.0,  # y
          0.0, 0.0, 1.0, 0.0, 0.0, 0.0,  # z
          0.0, 0.0, 0.0, 1.0, 0.0, 0.0,  # rotation x
          0.0, 0.0, 0.0, 0.0, 1.0, 0.0,  # rotation y
          0.0, 0.0, 0.0, 0.0, 0.0, 0.1   # rotation z
        ]
