/**:
  ros__parameters:
    camera_frame: camera
    # Intrinsics of the camera that is generating the vision detections
    camera_intrinsics:
        width: 1920
        height: 1080
        fx: 1158.0337
        fy: 1158.0337
        ox: 960.0
        oy: 540.0
        skew: 0.0
