# params/avp/lgsvl_simulation.param.yaml
---

/**:
  ros__parameters:
    # AutonomouStuff scene
    scene_uuid: 2aae5d39-a11c-4516-87c4-cdc9ca784551
    vehicle:
      # AWFLexus2016RXHybrid Autoware.Auto configuration
      config_uuid: c7d50f84-0a6b-4007-9b34-a723dc0e3d20
      # Vehicle spawn position
      spawn:
        position:
          x: -108.094
          y: -2.0545
          z: -28.905
        rotation:
          x: 1.641
          y: 141.217
          z: 359.085
